### ISSUE TITLE
Issue with ESPresense Adapter and Equal Usage of Two Tag Scanners

### ISSUE THREAD

**Issue by Flying-Bolt** [Grizzelbee/ioBroker.espresence#5]
**Content:**

I am using the ESPresense Adapter (version 0.4.4) in ioBroker with two ESP32 devices as tag scanners. The devices are named "device1 (room1) monitor#1" and "device2 (room2) monitor#2". I am monitoring the data point "espresense.0.devices.tile_c1087b685b86.presense" to detect the presence of persons.

**Initial Assumption:**

I assumed that both scanners are equal in terms of functionality. This means that the data point "espresense.0.devices.tile_c1087b685b86.presense" for tile:c1087b685b86 should be set to "true" as soon as one of the two scanners detects a tag and sends data to the MQTT server.

**Observed Issue:**

After turning off the scanner "device2 (room2) monitor#2", the data point is no longer set to "true", even though the other scanner still detects the tag (verified in the fingerprint and MQTT.Adapter). When I turn "device2 (room2) monitor#2" back on, the data point "espresense.0.devices.tile_c1087b685b86.presense" for tile:c1087b685b86 is correctly set to "true" when a tag is detected.

However, the opposite behavior is observed when turning off the scanner "device1 (room1) monitor#1". In this case, the data point is correctly set to "true" when the remaining scanner "device2 (room2) monitor#2" detects the tag.

Conclusion:

It seems that the ESPresense Adapter by default only considers the "presence" information from one scanner, specifically from "device2 (room2) monitor#2" in this example.

**Comment by Flying-Bolt** [comment]
JSON of espresense and mqtt
[espresense.0.json](https://github.com/Grizzelbee/ioBroker.espresence/files/14836718/espresense.0.json)
[mqtt.1.json](https://github.com/Grizzelbee/ioBroker.espresence/files/14836719/mqtt.1.json)

**Comment by Flying-Bolt** [comment]
Configuration of ESPresense ESP32
![monitor#2](https://github.com/Grizzelbee/ioBroker.espresence/assets/12726678/201e4fd9-d44e-4e43-8d38-a4e41dabadf5)
![monitor#1](https://github.com/Grizzelbee/ioBroker.espresence/assets/12726678/4ac5a270-2cfa-4498-bf54-d4289e91f917)

**Comment by Grizzelbee** [comment]
I'm very sorry, but you hit the wrong project.
It's true that I started writing an ESPresence adapter for ioBroker - but neither finished nor published it.
So the project you're looking for is: https://github.com/ticaki/ioBroker.espresense
